const app=document.getElementById('app');
const KEY='elmi-pm';
const stages=['Backlog','Requirements','Design','Development','Testing','UAT','Done'];
const seed={projects:[{id:'P-001',name:'One Muslim Platform',client:'Internal',stage:'Development',health:'On track',progress:68,due:'2026-10-15',owner:'Me'},{id:'P-002',name:'BeltBoyz Content System',client:'Internal',stage:'Planning',health:'At risk',progress:35,due:'2026-09-30',owner:'Me'},{id:'P-003',name:'Minnesota Vendor Operations',client:'Elmi Inc.',stage:'Execution',health:'On track',progress:52,due:'2026-11-20',owner:'Me'}],tasks:[{id:'T-001',title:'Finalize authentication flow',project:'One Muslim Platform',status:'Development',priority:'High',owner:'Me',due:'2026-09-14',progress:70,dependency:''},{id:'T-002',title:'Build project management board',project:'Elmi Dashboard',status:'Development',priority:'High',owner:'Me',due:'2026-09-12',progress:80,dependency:''},{id:'T-003',title:'Define content approval workflow',project:'BeltBoyz Content System',status:'Requirements',priority:'Medium',owner:'Me',due:'2026-09-18',progress:30,dependency:'T-001'},{id:'T-004',title:'Create Power Platform architecture',project:'Minnesota Vendor Operations',status:'Backlog',priority:'Medium',owner:'Me',due:'2026-09-25',progress:10,dependency:''},{id:'T-005',title:'User acceptance testing plan',project:'One Muslim Platform',status:'UAT',priority:'Low',owner:'Me',due:'2026-09-28',progress:50,dependency:'T-001'}],requirements:[{id:'R-001',title:'Users can create and assign work items',project:'Elmi Dashboard',status:'Approved',priority:'High',owner:'Me',dependency:''},{id:'R-002',title:'A task cannot enter UAT until its dependency is complete',project:'Elmi Dashboard',status:'Approved',priority:'High',owner:'Me',dependency:'T-002'},{id:'R-003',title:'Every project has an owner and due date',project:'All Projects',status:'Approved',priority:'Medium',owner:'Me',dependency:''}]};
let data=load(),page='dashboard';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch(e){return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function go(p){page=p;render()}
function nav(){return [['dashboard','▦','Dashboard'],['my-tasks','✓','My Tasks'],['projects','▣','Projects'],['board','▤','Work Board'],['requirements','≡','Requirements'],['timeline','◷','Timeline']]}
function shell(){return `<div class="shell"><aside class="sidebar"><div class="brand"><div class="brandmark">E</div><div><b>ELMI</b><span>PROJECT MANAGEMENT</span></div></div><nav class="nav"><div class="nav-label">Workspace</div>${nav().map(n=>`<button class="${page===n[0]?'active':''}" onclick="go('${n[0]}')"><span class="ico">${n[1]}</span><span>${n[2]}</span></button>`).join('')}<div class="nav-label">Create</div><button onclick="newProject()"><span class="ico">＋</span><span>New Project</span></button><button onclick="newTask()"><span class="ico">＋</span><span>New Work Item</span></button><button onclick="newReq()"><span class="ico">＋</span><span>New Requirement</span></button></nav><div class="sidebar-bottom"><button onclick="resetData()"><span class="ico">↻</span><span>Reset Demo</span></button></div></aside><main class="main"><header class="topbar"><div class="crumb">Elmi / ${title()}</div><div class="user"><span class="small muted">Owner · Project Manager</span><div class="avatar">AE</div></div></header><section class="content">${view()}</section></main></div>`}
function title(){return ({dashboard:'Dashboard','my-tasks':'My Tasks',projects:'Projects',board:'Work Board',requirements:'Requirements',timeline:'Timeline'})[page]||'Dashboard'}
function head(a,b,c=''){return `<div class="page-head"><div><h1>${a}</h1><p>${b}</p></div><div class="actions">${c}</div></div>`}
function view(){return page==='dashboard'?dashboard():page==='my-tasks'?tasks():page==='projects'?projects():page==='board'?board():page==='requirements'?requirements():timeline()}
function dashboard(){const open=data.tasks.filter(t=>t.status!=='Done').length,high=data.tasks.filter(t=>t.priority==='High'&&t.status!=='Done').length,avg=Math.round(data.projects.reduce((a,p)=>a+p.progress,0)/Math.max(1,data.projects.length));return head('Good afternoon, Abdulrazzaq 👋','Your personal command center for projects, work items, requirements and delivery.',`<button class="btn primary" onclick="newTask()">＋ New Work Item</button>`)+`<div class="grid stats"><div class="card stat"><div class="top"><span>Active Projects</span><span class="iconbox">▣</span></div><div class="value">${data.projects.length}</div><div class="trend">${data.projects.filter(p=>p.health==='On track').length} on track</div></div><div class="card stat"><div class="top"><span>Open Work</span><span class="iconbox">✓</span></div><div class="value">${open}</div><div class="trend">${high} high priority</div></div><div class="card stat"><div class="top"><span>Requirements</span><span class="iconbox">≡</span></div><div class="value">${data.requirements.length}</div><div class="trend">${data.requirements.filter(r=>r.status==='Approved').length} approved</div></div><div class="card stat"><div class="top"><span>Portfolio Progress</span><span class="iconbox">↗</span></div><div class="value">${avg}%</div><div class="trend">Across all projects</div></div></div><div class="grid two"><div class="card section"><div class="toolbar"><div><h3>My Work</h3><span class="small muted">Priority work requiring attention.</span></div><button class="btn" onclick="go('my-tasks')">View all</button></div>${data.tasks.filter(t=>t.status!=='Done').sort((a,b)=>rank(a.priority)-rank(b.priority)).slice(0,6).map(taskRow).join('')}</div><div class="card section"><div class="toolbar"><div><h3>Project Portfolio</h3><span class="small muted">Health and delivery progress.</span></div><button class="btn" onclick="go('projects')">Manage</button></div>${data.projects.map(p=>`<div class="listrow"><div style="flex:1"><b>${esc(p.name)}</b><div class="small muted">${esc(p.stage)} · Due ${esc(p.due)}</div><div class="progress"><i style="width:${p.progress}%"></i></div></div><span class="badge ${p.health==='On track'?'green':'amber'}">${p.progress}%</span></div>`).join('')}</div></div><div class="card section"><div class="toolbar"><div><h3>Agile Delivery Lifecycle</h3><span class="small muted">Work moves from idea to accepted delivery.</span></div><span class="badge blue">Controlled flow</span></div><div class="lifecycle">${stages.map((s,i)=>`<div><span>${i+1}</span><b>${s}</b></div>`).join('')}</div></div>`}
function rank(p){return p==='High'?0:p==='Medium'?1:2}
function taskRow(t){return `<div class="listrow"><div style="flex:1;cursor:pointer" onclick="editTask('${t.id}')"><b>${esc(t.title)}</b><div class="small muted">${esc(t.project)} · ${esc(t.status)} · Due ${esc(t.due)}</div></div><span class="badge ${t.priority==='High'?'red':t.priority==='Medium'?'amber':'green'}">${esc(t.priority)}</span></div>`}
function tasks(){return head('My Tasks','Everything assigned to you, with status, priority, dates and dependencies.',`<button class="btn primary" onclick="newTask()">＋ New Work Item</button>`)+`<div class="card section table-wrap"><table class="table"><thead><tr><th>ID</th><th>Work Item</th><th>Project</th><th>Status</th><th>Priority</th><th>Owner</th><th>Due</th><th>Progress</th><th></th></tr></thead><tbody>${data.tasks.map(t=>`<tr><td><b>${t.id}</b></td><td>${esc(t.title)}</td><td>${esc(t.project)}</td><td><span class="badge blue">${t.status}</span></td><td>${t.priority}</td><td>${esc(t.owner)}</td><td>${t.due}</td><td>${t.progress}%</td><td><button class="btn" onclick="editTask('${t.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div>`}
function projects(){return head('Projects','Your portfolio of active initiatives and delivery commitments.',`<button class="btn primary" onclick="newProject()">＋ New Project</button>`)+`<div class="grid three">${data.projects.map(p=>`<div class="card section"><div class="toolbar"><span class="badge ${p.health==='On track'?'green':'amber'}">${esc(p.health)}</span><button class="btn" onclick="editProject('${p.id}')">Edit</button></div><h3>${esc(p.name)}</h3><p class="small muted">${esc(p.client)} · Owner: ${esc(p.owner)}</p><p class="small muted">${esc(p.stage)} · Due ${esc(p.due)}</p><div class="progress"><i style="width:${p.progress}%"></i></div><b>${p.progress}% complete</b><div class="small muted" style="margin-top:10px">${data.tasks.filter(t=>t.project===p.name&&t.status!=='Done').length} open work items</div></div>`).join('')}</div>`}
function board(){return head('Work Board','Drag work through the Agile lifecycle. Dependencies are checked before a move is accepted.',`<button class="btn primary" onclick="newTask()">＋ Add Work Item</button>`)+`<div class="board">${stages.map(s=>`<div class="column" ondragover="event.preventDefault()" ondrop="dropTask(event,'${s}')"><div class="column-head"><b>${s}</b><span class="count">${data.tasks.filter(t=>t.status===s).length}</span></div>${data.tasks.filter(t=>t.status===s).map(t=>`<div class="task" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','${t.id}')" onclick="editTask('${t.id}')"><b>${esc(t.title)}</b><div class="small muted">${esc(t.project)}</div><div class="progress"><i style="width:${t.progress}%"></i></div><div class="task-meta"><span>${esc(t.owner)}</span><span class="priority ${t.priority.toLowerCase()}">${t.priority}</span></div>${t.dependency?`<div class="small muted">Depends on ${t.dependency}</div>`:''}</div>`).join('')}</div>`).join('')}</div>`}
function dropTask(e,status){const id=e.dataTransfer.getData('text/plain'),t=data.tasks.find(x=>x.id===id);if(!t)return;if(t.dependency){const d=data.tasks.find(x=>x.id===t.dependency);if(d&&d.status!=='Done'){toast(`Blocked: ${d.id} must be completed first.`);return}}t.status=status;if(status==='Done')t.progress=100;save();render();toast(`${t.id} moved to ${status}.`)}
function requirements(){return head('Requirements','Define what must be delivered, who owns it and what it depends on.',`<button class="btn primary" onclick="newReq()">＋ New Requirement</button>`)+`<div class="card section table-wrap"><table class="table"><thead><tr><th>ID</th><th>Requirement</th><th>Project</th><th>Status</th><th>Priority</th><th>Owner</th><th>Dependency</th><th></th></tr></thead><tbody>${data.requirements.map(r=>`<tr><td><b>${r.id}</b></td><td>${esc(r.title)}</td><td>${esc(r.project)}</td><td><span class="badge green">${esc(r.status)}</span></td><td>${esc(r.priority)}</td><td>${esc(r.owner)}</td><td>${esc(r.dependency||'None')}</td><td><button class="btn" onclick="editReq('${r.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div>`}
function timeline(){return head('Timeline','Upcoming work ordered by due date.',`<button class="btn primary" onclick="newTask()">＋ Schedule Work</button>`)+`<div class="card section">${[...data.tasks].sort((a,b)=>a.due.localeCompare(b.due)).map(t=>`<div class="listrow"><b style="width:110px">${t.due}</b><div style="flex:1"><b>${esc(t.title)}</b><div class="small muted">${esc(t.project)} · ${t.status}</div></div><span class="badge ${t.priority==='High'?'red':t.priority==='Medium'?'amber':'green'}">${t.priority}</span></div>`).join('')}</div>`}
function drawer(title,body,fn){closeDrawer();document.body.insertAdjacentHTML('beforeend',`<div class="drawer-backdrop" onclick="closeDrawer()"></div><aside class="drawer"><button class="close" onclick="closeDrawer()">×</button><h2>${title}</h2>${body}<button class="btn primary" id="saveDrawer" style="margin-top:22px;width:100%">Save</button></aside>`);document.getElementById('saveDrawer').onclick=fn}
function taskForm(t){return `<div class="form-grid"><div class="field full"><label>Work Item</label><input id="ft" value="${esc(t.title)}" placeholder="What needs to be done?"></div><div class="field"><label>Project</label><select id="fp">${data.projects.map(p=>`<option ${p.name===t.project?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Status</label><select id="fs">${stages.map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select id="fpr">${['High','Medium','Low'].map(s=>`<option ${s===t.priority?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Assignee</label><input id="fo" value="${esc(t.owner||'Me')}"></div><div class="field"><label>Due Date</label><input id="fd" type="date" value="${esc(t.due)}"></div><div class="field"><label>Progress %</label><input id="fpg" type="number" min="0" max="100" value="${t.progress||0}"></div><div class="field"><label>Dependency</label><select id="fdep"><option value="">None</option>${data.tasks.filter(x=>x.id!==t.id).map(x=>`<option value="${x.id}" ${x.id===t.dependency?'selected':''}>${x.id} — ${esc(x.title)}</option>`).join('')}</select></div></div><p class="small muted">Dependencies are checked when you move work on the board.</p>`}
function newTask(){drawer('New Work Item',taskForm({title:'',project:data.projects[0]?.name||'',status:'Backlog',priority:'Medium',owner:'Me',due:'',progress:0,dependency:''}),()=>saveTask('new'))}
function editTask(id){const t=data.tasks.find(x=>x.id===id);if(t)drawer(`Edit ${id}`,taskForm(t),()=>saveTask(id))}
function saveTask(id){let t=id==='new'?{id:`T-${String(data.tasks.length+1).padStart(3,'0')}`}:data.tasks.find(x=>x.id===id);Object.assign(t,{title:ft.value,project:fp.value,status:fs.value,priority:fpr.value,owner:fo.value||'Me',due:fd.value,progress:Math.min(100,Math.max(0,Number(fpg.value)||0)),dependency:fdep.value});if(id==='new')data.tasks.push(t);save();closeDrawer();render();toast('Work item saved.')}
function projectForm(p){return `<div class="form-grid"><div class="field full"><label>Project Name</label><input id="pn" value="${esc(p.name)}"></div><div class="field"><label>Client / Area</label><input id="pc" value="${esc(p.client)}"></div><div class="field"><label>Stage</label><input id="pst" value="${esc(p.stage)}"></div><div class="field"><label>Health</label><select id="ph"><option ${p.health==='On track'?'selected':''}>On track</option><option ${p.health==='At risk'?'selected':''}>At risk</option><option ${p.health==='Blocked'?'selected':''}>Blocked</option></select></div><div class="field"><label>Owner</label><input id="po" value="${esc(p.owner||'Me')}"></div><div class="field"><label>Due Date</label><input id="pd" type="date" value="${esc(p.due)}"></div><div class="field"><label>Progress %</label><input id="pp" type="number" min="0" max="100" value="${p.progress||0}"></div></div>`}
function newProject(){drawer('New Project',projectForm({name:'',client:'Internal',stage:'Planning',health:'On track',owner:'Me',due:'',progress:0}),()=>saveProject('new'))}
function editProject(id){const p=data.projects.find(x=>x.id===id);if(p)drawer(`Edit ${id}`,projectForm(p),()=>saveProject(id))}
function saveProject(id){let p=id==='new'?{id:`P-${String(data.projects.length+1).padStart(3,'0')}`}:data.projects.find(x=>x.id===id);Object.assign(p,{name:pn.value,client:pc.value,stage:pst.value,health:ph.value,owner:po.value||'Me',due:pd.value,progress:Math.min(100,Math.max(0,Number(pp.value)||0))});if(id==='new')data.projects.push(p);save();closeDrawer();render();toast('Project saved.')}
function reqForm(r){return `<div class="form-grid"><div class="field full"><label>Requirement</label><textarea id="rt" rows="4">${esc(r.title)}</textarea></div><div class="field"><label>Project</label><input id="rp" value="${esc(r.project)}"></div><div class="field"><label>Status</label><select id="rs"><option ${r.status==='Draft'?'selected':''}>Draft</option><option ${r.status==='Approved'?'selected':''}>Approved</option><option ${r.status==='Complete'?'selected':''}>Complete</option></select></div><div class="field"><label>Priority</label><select id="rr"><option ${r.priority==='High'?'selected':''}>High</option><option ${r.priority==='Medium'?'selected':''}>Medium</option><option ${r.priority==='Low'?'selected':''}>Low</option></select></div><div class="field"><label>Owner</label><input id="ro" value="${esc(r.owner||'Me')}"></div><div class="field full"><label>Dependency</label><input id="rd" value="${esc(r.dependency||'')}" placeholder="Optional work item ID"></div></div>`}
function newReq(){drawer('New Requirement',reqForm({title:'',project:data.projects[0]?.name||'',status:'Draft',priority:'Medium',owner:'Me',dependency:''}),()=>saveReq('new'))}
function editReq(id){const r=data.requirements.find(x=>x.id===id);if(r)drawer(`Edit ${id}`,reqForm(r),()=>saveReq(id))}
function saveReq(id){let r=id==='new'?{id:`R-${String(data.requirements.length+1).padStart(3,'0')}`}:data.requirements.find(x=>x.id===id);Object.assign(r,{title:rt.value,project:rp.value,status:rs.value,priority:rr.value,owner:ro.value||'Me',dependency:rd.value});if(id==='new')data.requirements.push(r);save();closeDrawer();render();toast('Requirement saved.')}
function closeDrawer(){document.querySelector('.drawer')?.remove();document.querySelector('.drawer-backdrop')?.remove()}
function resetData(){if(confirm('Reset the workspace to starter data?')){data=structuredClone(seed);save();render();toast('Workspace reset.')}}
render();
