const app = document.getElementById('app');
const KEY = 'elmi-pm';
const stages = ['Backlog','Requirements','Design','Development','Testing','UAT','Done'];
const types = ['Task','Fix','Goal Action','Personal','Business','Tech'];
const seed = {
  goals: [
    {id:'G-001', title:'Build a scalable business', area:'Business', status:'Active', progress:42, due:'2027-03-31', notes:'Win consulting work, staff delivery, and grow beyond owner-only capacity.'},
    {id:'G-002', title:'Keep life organized and moving', area:'Personal', status:'Active', progress:30, due:'2026-12-31', notes:'Use one system for real-life goals, fixes, projects, and commitments.'}
  ],
  projects: [
    {id:'P-001', name:'One Muslim Platform', client:'Internal', stage:'Development', health:'On track', progress:68, due:'2026-10-15', owner:'Me'},
    {id:'P-002', name:'BeltBoyz Content System', client:'Internal', stage:'Planning', health:'At risk', progress:35, due:'2026-09-30', owner:'Me'},
    {id:'P-003', name:'Minnesota Vendor Operations', client:'Elmi Inc.', stage:'Execution', health:'On track', progress:52, due:'2026-11-20', owner:'Me'}
  ],
  tasks: [
    {id:'T-001', title:'Finalize authentication flow', project:'One Muslim Platform', status:'Development', priority:'High', owner:'Me', due:'2026-09-14', progress:70, dependency:'', type:'Tech'},
    {id:'T-002', title:'Build project management board', project:'Elmi Dashboard', status:'Development', priority:'High', owner:'Me', due:'2026-09-12', progress:80, dependency:'', type:'Tech'},
    {id:'T-003', title:'Fix phone SOS issue', project:'Personal', status:'Requirements', priority:'High', owner:'Me', due:'2026-09-13', progress:20, dependency:'', type:'Fix'},
    {id:'T-004', title:'Define content approval workflow', project:'BeltBoyz Content System', status:'Requirements', priority:'Medium', owner:'Me', due:'2026-09-18', progress:30, dependency:'T-001', type:'Business'},
    {id:'T-005', title:'Create Power Platform architecture', project:'Minnesota Vendor Operations', status:'Backlog', priority:'Medium', owner:'Me', due:'2026-09-25', progress:10, dependency:'', type:'Tech'},
    {id:'T-006', title:'Study Allah\'s names', project:'Personal', status:'Backlog', priority:'Medium', owner:'Me', due:'2026-09-30', progress:15, dependency:'', type:'Personal'},
    {id:'T-007', title:'User acceptance testing plan', project:'One Muslim Platform', status:'UAT', priority:'Low', owner:'Me', due:'2026-09-28', progress:50, dependency:'T-001', type:'Tech'}
  ],
  requirements: [
    {id:'R-001', title:'Users can create and assign work items', project:'Elmi Dashboard', status:'Approved', priority:'High', owner:'Me', dependency:''},
    {id:'R-002', title:'A task cannot enter UAT until its dependency is complete', project:'Elmi Dashboard', status:'Approved', priority:'High', owner:'Me', dependency:'T-002'},
    {id:'R-003', title:'Every project has an owner and due date', project:'All Projects', status:'Approved', priority:'Medium', owner:'Me', dependency:''}
  ],
  inbox: []
};
let data = load();
let page = 'dashboard';

function load(){
  try {
    const saved = JSON.parse(localStorage.getItem(KEY));
    return saved && saved.tasks && saved.projects ? saved : structuredClone(seed);
  } catch(e){ return structuredClone(seed); }
}
function save(){ localStorage.setItem(KEY, JSON.stringify(data)); }
function esc(v){ return String(v ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }
function toast(text){ const el=document.createElement('div'); el.className='toast'; el.textContent=text; document.body.appendChild(el); setTimeout(()=>el.remove(),2200); }
function go(next){ page=next; render(); }
function rank(p){ return p==='High'?0:p==='Medium'?1:2; }
function today(){ return new Date().toISOString().slice(0,10); }
function nav(){ return [
  ['dashboard','▦','Dashboard'],['my-tasks','✓','My Work'],['projects','▣','Projects'],['board','▤','Work Board'],['goals','◎','Goals'],['requirements','≡','Requirements'],['timeline','◷','Timeline']
]; }
function title(){ return ({dashboard:'Dashboard','my-tasks':'My Work',projects:'Projects',board:'Work Board',goals:'Goals',requirements:'Requirements',timeline:'Timeline'})[page] || 'Dashboard'; }
function shell(){
  return `<div class="shell"><aside class="sidebar"><div class="brand"><div class="brandmark">E</div><div><b>ELMI</b><span>PROJECT + LIFE MANAGEMENT</span></div></div><nav class="nav"><div class="nav-label">Workspace</div>${nav().map(n=>`<button class="${page===n[0]?'active':''}" onclick="go('${n[0]}')"><span class="ico">${n[1]}</span><span>${n[2]}</span></button>`).join('')}<div class="nav-label">Create</div><button onclick="newTask()"><span class="ico">＋</span><span>New Work Item</span></button><button onclick="newGoal()"><span class="ico">＋</span><span>New Goal</span></button><button onclick="newProject()"><span class="ico">＋</span><span>New Project</span></button><button onclick="newReq()"><span class="ico">＋</span><span>New Requirement</span></button></nav><div class="sidebar-bottom"><button onclick="resetData()"><span class="ico">↻</span><span>Reset Demo</span></button></div></aside><main class="main"><header class="topbar"><div class="crumb">Elmi / ${title()}</div><div class="user"><span class="small muted">Owner · Project Manager</span><div class="avatar">AE</div></div></header><section class="content">${view()}</section></main></div>`;
}
function head(a,b,c=''){ return `<div class="page-head"><div><h1>${a}</h1><p>${b}</p></div><div class="actions">${c}</div></div>`; }
function view(){ return page==='dashboard'?dashboard():page==='my-tasks'?tasks():page==='projects'?projects():page==='board'?board():page==='goals'?goals():page==='requirements'?requirements():timeline(); }
function dashboard(){
  const open=data.tasks.filter(t=>t.status!=='Done').length;
  const high=data.tasks.filter(t=>t.priority==='High'&&t.status!=='Done').length;
  const avg=Math.round(data.projects.reduce((a,p)=>a+p.progress,0)/Math.max(1,data.projects.length));
  const due=data.tasks.filter(t=>t.status!=='Done'&&t.due&&t.due<=today()).length;
  return head('Good afternoon, Abdulrazzaq 👋','One place for the things you are trying to accomplish — business, tech, personal goals, and real-life fixes.',`<button class="btn primary" onclick="newTask()">＋ Add Anything</button>`)+
  `<div class="grid stats"><div class="card stat"><div class="top"><span>Active Goals</span><span class="iconbox">◎</span></div><div class="value">${data.goals.length}</div><div class="trend">${data.goals.filter(g=>g.status==='Active').length} active</div></div><div class="card stat"><div class="top"><span>Open Work</span><span class="iconbox">✓</span></div><div class="value">${open}</div><div class="trend">${high} high priority</div></div><div class="card stat"><div class="top"><span>Projects</span><span class="iconbox">▣</span></div><div class="value">${data.projects.length}</div><div class="trend">${data.projects.filter(p=>p.health==='On track').length} on track</div></div><div class="card stat"><div class="top"><span>Needs Attention</span><span class="iconbox">!</span></div><div class="value">${due}</div><div class="trend">Due or overdue</div></div></div>
  <div class="grid two"><div class="card section"><div class="toolbar"><div><h3>Everything On Your Plate</h3><span class="small muted">Not just work. Anything you need to move forward.</span></div><button class="btn" onclick="go('my-tasks')">View all</button></div>${data.tasks.filter(t=>t.status!=='Done').sort((a,b)=>rank(a.priority)-rank(b.priority)).slice(0,7).map(taskRow).join('')||empty('Nothing open right now.')}</div>
  <div class="card section"><div class="toolbar"><div><h3>Goals</h3><span class="small muted">The outcomes behind the work.</span></div><button class="btn" onclick="go('goals')">Manage</button></div>${data.goals.map(g=>`<div class="listrow"><div style="flex:1"><b>${esc(g.title)}</b><div class="small muted">${esc(g.area)} · Due ${esc(g.due)}</div><div class="progress"><i style="width:${g.progress}%"></i></div></div><span class="badge blue">${g.progress}%</span></div>`).join('')||empty('No goals yet.')}</div></div>
  <div class="card section"><div class="toolbar"><div><h3>Quick Capture</h3><span class="small muted">Turn a thought, problem, or commitment into something trackable.</span></div></div><div class="capture"><input id="quickCapture" placeholder="e.g. Fix my phone, call a client, finish a proposal, study tonight..."><button class="btn primary" onclick="capture()">Capture</button></div></div>
  <div class="card section"><div class="toolbar"><div><h3>Project Portfolio</h3><span class="small muted">Delivery commitments currently in motion.</span></div><button class="btn" onclick="go('projects')">Manage</button></div>${data.projects.map(p=>`<div class="listrow"><div style="flex:1"><b>${esc(p.name)}</b><div class="small muted">${esc(p.stage)} · Due ${esc(p.due)}</div><div class="progress"><i style="width:${p.progress}%"></i></div></div><span class="badge ${p.health==='On track'?'green':'amber'}">${p.progress}%</span></div>`).join('')}</div>`;
}
function taskRow(t){ return `<div class="listrow"><div style="flex:1;cursor:pointer" onclick="editTask('${t.id}')"><div class="item-title"><b>${esc(t.title)}</b><span class="badge type-badge">${esc(t.type||'Task')}</span></div><div class="small muted">${esc(t.project)} · ${esc(t.status)} · Due ${esc(t.due||'No date')}</div></div><span class="badge ${t.priority==='High'?'red':t.priority==='Medium'?'amber':'green'}">${esc(t.priority)}</span></div>`; }
function tasks(){
  return head('My Work','A universal list for projects, goals, fixes, personal tasks, business actions, and tech work.',`<button class="btn primary" onclick="newTask()">＋ Add Work</button>`)+
  `<div class="filterbar card"><div><b>Everything</b><span class="small muted"> ${data.tasks.length} total items</span></div><div class="filter-pills"><button class="filter active" onclick="filterTasks('all',this)">All</button><button class="filter" onclick="filterTasks('open',this)">Open</button><button class="filter" onclick="filterTasks('high',this)">High Priority</button><button class="filter" onclick="filterTasks('Fix',this)">Fixes</button><button class="filter" onclick="filterTasks('Personal',this)">Personal</button><button class="filter" onclick="filterTasks('Business',this)">Business</button><button class="filter" onclick="filterTasks('Tech',this)">Tech</button></div></div><div id="taskTable" class="card section table-wrap">${taskTable(data.tasks)}</div>`;
}
function taskTable(list){ return `<table class="table"><thead><tr><th>ID</th><th>Work</th><th>Type</th><th>Project / Area</th><th>Status</th><th>Priority</th><th>Due</th><th>Progress</th><th></th></tr></thead><tbody>${list.map(t=>`<tr><td><b>${t.id}</b></td><td>${esc(t.title)}</td><td><span class="badge type-badge">${esc(t.type||'Task')}</span></td><td>${esc(t.project)}</td><td><span class="badge blue">${esc(t.status)}</span></td><td>${esc(t.priority)}</td><td>${esc(t.due||'—')}</td><td>${t.progress||0}%</td><td><button class="btn" onclick="editTask('${t.id}')">Edit</button></td></tr>`).join('')||`<tr><td colspan="9" class="muted">Nothing matches this filter.</td></tr>`}</tbody></table>`; }
function filterTasks(kind,button){ document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active')); button.classList.add('active'); let list=data.tasks; if(kind==='open') list=list.filter(t=>t.status!=='Done'); else if(kind==='high') list=list.filter(t=>t.priority==='High'&&t.status!=='Done'); else if(['Fix','Personal','Business','Tech'].includes(kind)) list=list.filter(t=>t.type===kind); document.getElementById('taskTable').innerHTML=taskTable(list); }
function projects(){ return head('Projects','Initiatives with a defined outcome, owner, and delivery commitment.',`<button class="btn primary" onclick="newProject()">＋ New Project</button>`)+`<div class="grid three">${data.projects.map(p=>`<div class="card section"><div class="toolbar"><span class="badge ${p.health==='On track'?'green':'amber'}">${esc(p.health)}</span><button class="btn" onclick="editProject('${p.id}')">Edit</button></div><h3>${esc(p.name)}</h3><p class="small muted">${esc(p.client)} · Owner: ${esc(p.owner)}</p><p class="small muted">${esc(p.stage)} · Due ${esc(p.due)}</p><div class="progress"><i style="width:${p.progress}%"></i></div><b>${p.progress}% complete</b><div class="small muted" style="margin-top:10px">${data.tasks.filter(t=>t.project===p.name&&t.status!=='Done').length} open work items</div></div>`).join('')}</div>`; }
function board(){ return head('Work Board','Drag work through the delivery lifecycle. This board is for work items, whether technical or real-life.',`<button class="btn primary" onclick="newTask()">＋ Add Work</button>`)+`<div class="board">${stages.map(s=>`<div class="column" ondragover="event.preventDefault()" ondrop="dropTask(event,'${s}')"><div class="column-head"><b>${s}</b><span class="count">${data.tasks.filter(t=>t.status===s).length}</span></div>${data.tasks.filter(t=>t.status===s).map(t=>`<div class="task" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','${t.id}')" onclick="editTask('${t.id}')"><div class="item-title"><span class="task-title">${esc(t.title)}</span><span class="badge type-badge">${esc(t.type||'Task')}</span></div><div class="small muted">${esc(t.project)}</div><div class="progress"><i style="width:${t.progress}%"></i></div><div class="task-meta"><span>${esc(t.owner)}</span><span class="priority ${String(t.priority).toLowerCase()}">${esc(t.priority)}</span></div>${t.dependency?`<div class="small muted">Depends on ${esc(t.dependency)}</div>`:''}</div>`).join('')||`<div class="small muted empty-column">Drop work here</div>`}</div>`).join('')}</div>`; }
function dropTask(e,status){ const id=e.dataTransfer.getData('text/plain'); const t=data.tasks.find(x=>x.id===id); if(!t)return; if(t.dependency){const d=data.tasks.find(x=>x.id===t.dependency); if(d&&d.status!=='Done'){toast(`Blocked: ${d.id} must be completed first.`);return;}} t.status=status; if(status==='Done')t.progress=100; save(); render(); toast(`${t.id} moved to ${status}.`); }
function goals(){ return head('Goals','Outcomes you care about. Projects and work items can support a goal, but a goal can also stand alone.',`<button class="btn primary" onclick="newGoal()">＋ New Goal</button>`)+`<div class="grid two">${data.goals.map(g=>`<div class="card section goal-card"><div class="toolbar"><span class="badge ${g.status==='Active'?'green':'blue'}">${esc(g.status)}</span><button class="btn" onclick="editGoal('${g.id}')">Edit</button></div><h3>${esc(g.title)}</h3><p class="small muted">${esc(g.area)} · Due ${esc(g.due)}</p><p class="small">${esc(g.notes||'')}</p><div class="progress"><i style="width:${g.progress}%"></i></div><b>${g.progress}% progress</b><div class="goal-actions"><button class="btn" onclick="goalWork('${g.id}')">View supporting work</button></div></div>`).join('')||empty('No goals yet. Create one when you have an outcome you want to achieve.')}</div>`; }
function goalWork(id){ const g=data.goals.find(x=>x.id===id); if(!g)return; go('my-tasks'); setTimeout(()=>{ const list=data.tasks.filter(t=>t.project===g.title); if(list.length) document.getElementById('taskTable').innerHTML=taskTable(list); },0); }
function requirements(){ return head('Requirements','Rules and conditions that define what good delivery looks like.',`<button class="btn primary" onclick="newReq()">＋ New Requirement</button>`)+`<div class="card section table-wrap"><table class="table"><thead><tr><th>ID</th><th>Requirement</th><th>Project</th><th>Status</th><th>Priority</th><th>Owner</th><th>Dependency</th><th></th></tr></thead><tbody>${data.requirements.map(r=>`<tr><td><b>${r.id}</b></td><td>${esc(r.title)}</td><td>${esc(r.project)}</td><td><span class="badge green">${esc(r.status)}</span></td><td>${esc(r.priority)}</td><td>${esc(r.owner)}</td><td>${esc(r.dependency||'None')}</td><td><button class="btn" onclick="editReq('${r.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div>`; }
function timeline(){ return head('Timeline','Upcoming work and commitments ordered by due date.',`<button class="btn primary" onclick="newTask()">＋ Schedule Work</button>`)+`<div class="card section">${[...data.tasks].filter(t=>t.due).sort((a,b)=>a.due.localeCompare(b.due)).map(t=>`<div class="listrow"><b style="width:110px">${esc(t.due)}</b><div style="flex:1"><div class="item-title"><b>${esc(t.title)}</b><span class="badge type-badge">${esc(t.type||'Task')}</span></div><div class="small muted">${esc(t.project)} · ${esc(t.status)}</div></div><span class="badge ${t.priority==='High'?'red':t.priority==='Medium'?'amber':'green'}">${esc(t.priority)}</span></div>`).join('')||empty('No dated work.')}</div>`; }
function empty(text){ return `<div class="empty-state">${esc(text)}</div>`; }
function drawer(titleText,body,fn){ closeDrawer(); document.body.insertAdjacentHTML('beforeend',`<div class="drawer-backdrop" onclick="closeDrawer()"></div><aside class="drawer"><button class="close" onclick="closeDrawer()">×</button><h2>${titleText}</h2>${body}<button class="btn primary" id="saveDrawer" style="margin-top:22px;width:100%">Save</button></aside>`); document.getElementById('saveDrawer').onclick=fn; }
function taskForm(t){ return `<div class="form-grid"><div class="field full"><label>What needs to happen?</label><input id="ft" value="${esc(t.title)}" placeholder="Fix my phone, finish proposal, build feature..."></div><div class="field"><label>Type</label><select id="fty">${types.map(s=>`<option ${s===(t.type||'Task')?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Project / Area</label><input id="fp" value="${esc(t.project||'Personal')}" placeholder="Project, Personal, Business..."></div><div class="field"><label>Status</label><select id="fs">${stages.map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select id="fpr">${['High','Medium','Low'].map(s=>`<option ${s===t.priority?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Assignee</label><input id="fo" value="${esc(t.owner||'Me')}"></div><div class="field"><label>Due Date</label><input id="fd" type="date" value="${esc(t.due||'')}"></div><div class="field"><label>Progress %</label><input id="fpg" type="number" min="0" max="100" value="${t.progress||0}"></div><div class="field full"><label>Dependency</label><select id="fdep"><option value="">None</option>${data.tasks.filter(x=>x.id!==t.id).map(x=>`<option value="${x.id}" ${x.id===t.dependency?'selected':''}>${x.id} — ${esc(x.title)}</option>`).join('')}</select></div></div><p class="small muted">A work item can be a technical task, a real-life fix, a business action, or anything else you need to move forward.</p>`; }
function newTask(){ drawer('Add Anything',taskForm({title:'',project:'Personal',status:'Backlog',priority:'Medium',owner:'Me',due:'',progress:0,dependency:'',type:'Task'}),()=>saveTask('new')); }
function editTask(id){ const t=data.tasks.find(x=>x.id===id); if(t)drawer(`Edit ${id}`,taskForm(t),()=>saveTask(id)); }
function saveTask(id){ let t=id==='new'?{id:`T-${String(data.tasks.length+1).padStart(3,'0')}`}:data.tasks.find(x=>x.id===id); if(!t)return; Object.assign(t,{title:ft.value.trim()||'Untitled work',type:fty.value,project:fp.value.trim()||'Personal',status:fs.value,priority:fpr.value,owner:fo.value.trim()||'Me',due:fd.value,progress:Math.max(0,Math.min(100,Number(fpg.value)||0)),dependency:fdep.value}); if(t.status==='Done')t.progress=100; if(id==='new')data.tasks.push(t); save(); closeDrawer(); render(); toast(`${t.id} saved.`); }
function projectForm(p){ return `<div class="form-grid"><div class="field full"><label>Project Name</label><input id="pn" value="${esc(p.name)}" placeholder="What are you building or accomplishing?"></div><div class="field"><label>Client / Area</label><input id="pc" value="${esc(p.client||'Internal')}"></div><div class="field"><label>Stage</label><input id="ps" value="${esc(p.stage||'Planning')}"></div><div class="field"><label>Health</label><select id="ph"><option ${p.health==='On track'?'selected':''}>On track</option><option ${p.health==='At risk'?'selected':''}>At risk</option><option ${p.health==='Blocked'?'selected':''}>Blocked</option></select></div><div class="field"><label>Owner</label><input id="po" value="${esc(p.owner||'Me')}"></div><div class="field"><label>Due Date</label><input id="pd" type="date" value="${esc(p.due||'')}"></div><div class="field"><label>Progress %</label><input id="pp" type="number" min="0" max="100" value="${p.progress||0}"></div></div>`; }
function newProject(){ drawer('New Project',projectForm({name:'',client:'Internal',stage:'Planning',health:'On track',owner:'Me',due:'',progress:0}),()=>saveProject('new')); }
function editProject(id){ const p=data.projects.find(x=>x.id===id); if(p)drawer(`Edit ${id}`,projectForm(p),()=>saveProject(id)); }
function saveProject(id){ let p=id==='new'?{id:`P-${String(data.projects.length+1).padStart(3,'0')}`}:data.projects.find(x=>x.id===id); Object.assign(p,{name:pn.value.trim()||'Untitled Project',client:pc.value.trim()||'Internal',stage:ps.value.trim()||'Planning',health:ph.value,owner:po.value.trim()||'Me',due:pd.value,progress:Math.max(0,Math.min(100,Number(pp.value)||0))}); if(id==='new')data.projects.push(p); save(); closeDrawer(); render(); toast(`${p.id} saved.`); }
function goalForm(g){ return `<div class="form-grid"><div class="field full"><label>Goal</label><input id="gn" value="${esc(g.title)}" placeholder="What outcome do you want?"></div><div class="field"><label>Area</label><select id="ga"><option ${g.area==='Personal'?'selected':''}>Personal</option><option ${g.area==='Business'?'selected':''}>Business</option><option ${g.area==='Faith'?'selected':''}>Faith</option><option ${g.area==='Health'?'selected':''}>Health</option><option ${g.area==='Career'?'selected':''}>Career</option></select></div><div class="field"><label>Status</label><select id="gs"><option ${g.status==='Active'?'selected':''}>Active</option><option ${g.status==='Paused'?'selected':''}>Paused</option><option ${g.status==='Complete'?'selected':''}>Complete</option></select></div><div class="field"><label>Due Date</label><input id="gd" type="date" value="${esc(g.due||'')}"></div><div class="field"><label>Progress %</label><input id="gp" type="number" min="0" max="100" value="${g.progress||0}"></div><div class="field full"><label>Why / Notes</label><textarea id="gnotes" rows="5" placeholder="Why does this matter? What does success look like?">${esc(g.notes||'')}</textarea></div></div>`; }
function newGoal(){ drawer('New Goal',goalForm({title:'',area:'Personal',status:'Active',due:'',progress:0,notes:''}),()=>saveGoal('new')); }
function editGoal(id){ const g=data.goals.find(x=>x.id===id); if(g)drawer(`Edit ${id}`,goalForm(g),()=>saveGoal(id)); }
function saveGoal(id){ let g=id==='new'?{id:`G-${String(data.goals.length+1).padStart(3,'0')}`}:data.goals.find(x=>x.id===id); Object.assign(g,{title:gn.value.trim()||'Untitled Goal',area:ga.value,status:gs.value,due:gd.value,progress:Math.max(0,Math.min(100,Number(gp.value)||0)),notes:gnotes.value.trim()}); if(id==='new')data.goals.push(g); save(); closeDrawer(); render(); toast(`${g.id} saved.`); }
function reqForm(r){ return `<div class="form-grid"><div class="field full"><label>Requirement</label><textarea id="rn" rows="4" placeholder="What must be true or delivered?">${esc(r.title)}</textarea></div><div class="field"><label>Project / Area</label><input id="rp" value="${esc(r.project||'All Projects')}"></div><div class="field"><label>Status</label><select id="rs"><option ${r.status==='Draft'?'selected':''}>Draft</option><option ${r.status==='Approved'?'selected':''}>Approved</option><option ${r.status==='Rejected'?'selected':''}>Rejected</option></select></div><div class="field"><label>Priority</label><select id="rr">${['High','Medium','Low'].map(s=>`<option ${s===r.priority?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Owner</label><input id="ro" value="${esc(r.owner||'Me')}"></div></div>`; }
function newReq(){ drawer('New Requirement',reqForm({title:'',project:'All Projects',status:'Draft',priority:'Medium',owner:'Me'}),()=>saveReq('new')); }
function editReq(id){ const r=data.requirements.find(x=>x.id===id); if(r)drawer(`Edit ${id}`,reqForm(r),()=>saveReq(id)); }
function saveReq(id){ let r=id==='new'?{id:`R-${String(data.requirements.length+1).padStart(3,'0')}`}:data.requirements.find(x=>x.id===id); Object.assign(r,{title:rn.value.trim()||'Untitled Requirement',project:rp.value.trim()||'All Projects',status:rs.value,priority:rr.value,owner:ro.value.trim()||'Me',dependency:''}); if(id==='new')data.requirements.push(r); save(); closeDrawer(); render(); toast(`${r.id} saved.`); }
function capture(){ const input=document.getElementById('quickCapture'); const text=input?.value.trim(); if(!text)return; const t={id:`T-${String(data.tasks.length+1).padStart(3,'0')}`,title:text,project:'Personal',status:'Backlog',priority:'Medium',owner:'Me',due:'',progress:0,dependency:'',type:'Personal'}; data.tasks.push(t); save(); render(); toast('Captured as a work item.'); }
function closeDrawer(){ document.querySelectorAll('.drawer,.drawer-backdrop').forEach(e=>e.remove()); }
function resetData(){ if(confirm('Reset the dashboard to the starter data?')){data=structuredClone(seed);save();render();toast('Demo data restored.');} }
function render(){ app.innerHTML=shell(); }
window.go=go; window.newTask=newTask; window.editTask=editTask; window.newProject=newProject; window.editProject=editProject; window.newGoal=newGoal; window.editGoal=editGoal; window.newReq=newReq; window.editReq=editReq; window.dropTask=dropTask; window.filterTasks=filterTasks; window.capture=capture; window.closeDrawer=closeDrawer; window.resetData=resetData; window.goalWork=goalWork;
render();
