const app=document.getElementById('app');
const STORAGE='elmi-pm-v1';
const defaultData={projects:[{id:'P-001',name:'One Muslim Platform',client:'Internal',stage:'Development',health:'On track',progress:68,due:'2026-10-15',owner:'Me'},{id:'P-002',name:'BeltBoyz Content System',client:'Internal',stage:'Planning',health:'At risk',progress:35,due:'2026-09-30',owner:'Me'},{id:'P-003',name:'Minnesota Vendor Operations',client:'Elmi Inc.',stage:'Execution',health:'On track',progress:52,due:'2026-11-20',owner:'Me'}],tasks:[{id:'T-001',title:'Finalize authentication flow',project:'One Muslim Platform',status:'Development',priority:'High',owner:'Me',due:'2026-09-14',progress:70,dependency:''},{id:'T-002',title:'Build project management board',project:'Elmi Inc. Dashboard',status:'Development',priority:'High',owner:'Me',due:'2026-09-12',progress:80,dependency:''},{id:'T-003',title:'Define content approval workflow',project:'BeltBoyz Content System',status:'Requirements',priority:'Medium',owner:'Me',due:'2026-09-18',progress:30,dependency:'T-001'},{id:'T-004',title:'Create Power Platform architecture',project:'Minnesota Vendor Operations',status:'Backlog',priority:'Medium',owner:'Me',due:'2026-09-25',progress:10,dependency:''},{id:'T-005',title:'User acceptance testing plan',project:'One Muslim Platform',status:'UAT',priority:'Low',owner:'Me',due:'2026-09-28',progress:50,dependency:'T-001'}],requirements:[{id:'R-001',title:'Users can create and assign work items',project:'Elmi Inc. Dashboard',status:'Approved',priority:'High',owner:'Me',dependency:''},{id:'R-002',title:'A task cannot enter UAT until development is complete',project:'Elmi Inc. Dashboard',status:'Approved',priority:'High',owner:'Me',dependency:'T-002'},{id:'R-003',title:'Every project has an owner and due date',project:'All Projects',status:'Approved',priority:'Medium',owner:'Me',dependency:''}]};
let data=load();let page='dashboard';let filterProject='All';
function load(){try{return JSON.parse(localStorage.getItem(STORAGE))||structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(data));}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function shell(){return `<div class="shell"><aside class="sidebar"><div class="brand"><div class="brandmark">E</div><div><b>ELMI</b><span>PROJECT OS</span></div></div><nav class="nav"><div class="nav-label">Workspace</div>${[['dashboard','▦','Dashboard'],['my-tasks','✓','My Tasks'],['projects','▣','Projects'],['board','▤','Work Board'],['requirements','≡','Requirements'],['timeline','◷','Timeline']].map(n=>`<button class="${page===n[0]?'active':''}" onclick="go('${n[0]}')"><span class="ico">${n[1]}</span><span>${n[2]}</span></button>`).join('')}<div class="nav-label">Management</div><button onclick="newProject()"><span class="ico">＋</span><span>New Project</span></button><button onclick="newTask()"><span class="ico">＋</span><span>New Work Item</span></button><button onclick="newRequirement()"><span class="ico">＋</span><span>New Requirement</span></button></nav><div class="sidebar-bottom"><button onclick="resetData()"><span class="ico">↻</span><span>Reset Demo Data</span></button></div></aside><main class="main"><header class="topbar"><div class="crumb">Elmi / ${pageLabel()}</div><div class="user"><span class="small muted">Owner / Project Manager</span><div class="avatar">AE</div></div></header><section class="content">${pageView()}</section></main></div>`}
function pageLabel(){return ({dashboard:'Dashboard','my-tasks':'My Tasks',projects:'Projects',board:'Work Board',requirements:'Requirements',timeline:'Timeline'})[page]||'Workspace'}
function head(title,sub,buttons=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${buttons}</div></div>`}
function pageView(){switch(page){case'dashboard':return dashboard();case'my-tasks':return tasksPage(true);case'projects':return projectsPage();case'board':return boardPage();case'requirements':return reqPage();case'timeline':return timelinePage();default:return dashboard()}}
function dashboard(){const open=data.tasks.filter(t=>t.status!=='Done').length,done=data.tasks.filter(t=>t.status==='Done').length,high=data.tasks.filter(t=>t.priority==='High'&&t.status!=='Done').length;return head('Good afternoon, Abdulrazzaq 👋','Your personal command center for projects, work items, requirements and delivery.',`<button class="btn primary" onclick="newTask()">＋ New Work Item</button>`)+`<div class="grid stats"><div class="card stat"><div class="top"><span>Active Projects</span><span class="iconbox">▣</span></div><div class="value">${data.projects.length}</div><div class="trend">${data.projects.filter(p=>p.health==='On track').length} on track</div></div><div class="card stat"><div class="top"><span>Open Work Items</span><span class="iconbox">✓</span></div><div class="value">${open}</div><div class="trend">${high} high priority</div></div><div class="card stat"><div class="top"><span>Completed</span><span class="iconbox">✓</span></div><div class="value">${done}</div><div class="trend">Across all projects</div></div><div class="card stat"><div class="top"><span>Overall Progress</span><span class="iconbox">↗</span></div><div class="value">${overall()}%</div><div class="trend">Project portfolio</div></div></div><div class="grid two"><div class="card section"><div class="toolbar"><div><h3>My Work</h3><span class="small muted">Highest priority items requiring attention.</span></div><button class="btn" onclick="go('my-tasks')">View all</button></div>${data.tasks.filter(t=>t.status!=='Done').sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)).slice(0,5).map(taskRow).join('')}</div><div class="card section"><div class="toolbar"><div><h3>Project Portfolio</h3><span class="small muted">Current delivery health.</span></div><button class="btn" onclick="go('projects')">Manage</button></div>${data.projects.map(p=>`<div class="listrow"><div style="flex:1"><b>${esc(p.name)}</b><div class="small muted">${esc(p.stage)} · Due ${esc(p.due)}</div><div class="progress"><i style="width:${p.progress}%"></i></div></div><span class="badge ${p.health==='On track'?'green':'amber'}">${p.progress}%</span></div>`).join('')}</div></div><div class="card section"><div class="toolbar"><div><h3>Delivery Rules</h3><span class="small muted">Dependencies are enforced before moving work forward.</span></div><span class="badge blue">Agile</span></div><div class="grid three"><div><b>Backlog → Requirements</b><div class="small muted">Clarify what must be built.</div></div><div><b>Design → Development → Testing</b><div class="small muted">Build and validate.</div></div><div><b>UAT → Done</b><div class="small muted">Complete acceptance before closure.</div></div></div></div>`}
function overall(){if(!data.projects.length)return 0;return Math.round(data.projects.reduce((a,p)=>a+p.progress,0)/data.projects.length)}
function priorityRank(p){return p==='High'?0:p==='Medium'?1:2}
function taskRow(t){return `<div class="listrow"><div style="flex:1;cursor:pointer" onclick="editTask('${t.id}')"><b>${esc(t.title)}</b><div class="small muted">${esc(t.project)} · ${esc(t.status)} · Due ${esc(t.due)}</div></div><span class="badge ${t.priority==='High'?'red':t.priority==='Medium'?'amber':'green'}">${esc(t.priority)}</span></div>`}
function tasksPage(onlyMine=false){let arr=data.tasks.filter(t=>!onlyMine||t.owner==='Me');if(filterProject!=='All')arr=arr.filter(t=>t.project===filterProject);return head('My Tasks','Every work item is owned, scheduled, prioritized and connected to its project.',`<select onchange="filterProject=this.value;render()"><option>All</option>${data.projects.map(p=>`<option ${filterProject===p.name?'selected':''}>${esc(p.name)}</option>`).join('')}</select><button class="btn primary" onclick="newTask()">＋ New Work Item</button>`)+`<div class="card section"><div class="table-wrap"><table class="table"><thead><tr><th>Work Item</th><th>Project</th><th>Status</th><th>Priority</th><th>Owner</th><th>Due</th><th>Progress</th><th></th></tr></thead><tbody>${arr.map(t=>`<tr><td><b>${esc(t.id)}</b><br><span style="cursor:pointer" onclick="editTask('${t.id}')">${esc(t.title)}</span></td><td>${esc(t.project)}</td><td><span class="badge blue">${esc(t.status)}</span></td><td><span class="priority ${t.priority.toLowerCase()}">${esc(t.priority)}</span></td><td>${esc(t.owner)}</td><td>${esc(t.due)}</td><td><div class="progress" style="width:100px"><i style="width:${t.progress}%"></i></div><span class="small muted">${t.progress}%</span></td><td><button class="btn" onclick="editTask('${t.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div></div>`}
function projectsPage(){return head('Projects','Manage your project portfolio, ownership, health, deadlines and delivery progress.',`<button class="btn primary" onclick="newProject()">＋ New Project</button>`)+`<div class="grid three">${data.projects.map(p=>`<div class="card section"><div class="toolbar"><span class="badge ${p.health==='On track'?'green':'amber'}">${esc(p.health)}</span><button class="btn" onclick="editProject('${p.id}')">Edit</button></div><h3>${esc(p.name)}</h3><p class="small muted">${esc(p.client)} · Owner: ${esc(p.owner)}</p><div class="small muted">${esc(p.stage)} · Due ${esc(p.due)}</div><div class="progress"><i style="width:${p.progress}%"></i></div><b>${p.progress}% complete</b><div class="small muted" style="margin-top:12px">${data.tasks.filter(t=>t.project===p.name&&t.status!=='Done').length} open work items</div></div>`).join('')}</div>`}
const stages=['Backlog','Requirements','Design','Development','Testing','UAT','Done'];
function boardPage(){return head('Work Board','Move work through the Agile development lifecycle. Dependencies are checked before progression.',`<button class="btn primary" onclick="newTask()">＋ Add Work Item</button>`)+`<div class="board">${stages.map(s=>`<div class="column" ondragover="event.preventDefault()" ondrop="dropTask(event,'${s}')"><div class="column-head"><span class="column-title">${s}</span><span class="count">${data.tasks.filter(t=>t.status===s).length}</span></div>${data.tasks.filter(t=>t.status===s).map(t=>`<div class="task" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','${t.id}')" onclick="editTask('${t.id}')"><div class="task-title">${esc(t.title)}</div><div class="small muted" style="margin-top:7px">${esc(t.project)}</div><div class="progress"><i style="width:${t.progress}%"></i></div><div class="task-meta"><span>${esc(t.owner)}</span><span class="priority ${t.priority.toLowerCase()}">${esc(t.priority)}</span></div></div>`).join('')}</div>`).join('')}</div>`}
function dropTask(e,status){const id=e.dataTransfer.getData('text/plain');const t=data.tasks.find(x=>x.id===id);if(!t)return;if(t.dependency){const d=data.tasks.find(x=>x.id===t.dependency);if(d&&d.status!=='Done'){toast(`Blocked: ${t.dependency} must be completed first.`);return}}t.status=status;t.progress=status==='Done'?100:Math.max(t.progress,status==='UAT'?75:t.progress);save();render();toast(`${t.id} moved to ${status}.`)}
function reqPage(){return head('Requirements','Define the work that must be completed, with owners and dependencies.',`<button class="btn primary" onclick="newRequirement()">＋ New Requirement</button>`)+`<div class="card section"><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Requirement</th><th>Project</th><th>Status</th><th>Priority</th><th>Owner</th><th>Dependency</th><th></th></tr></thead><tbody>${data.requirements.map(r=>`<tr><td><b>${r.id}</b></td><td>${esc(r.title)}</td><td>${esc(r.project)}</td><td><span class="badge green">${esc(r.status)}</span></td><td>${esc(r.priority)}</td><td>${esc(r.owner)}</td><td>${esc(r.dependency||'None')}</td><td><button class="btn" onclick="editRequirement('${r.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div></div>`}
function timelinePage(){return head('Timeline','A simple delivery view of project milestones and upcoming work.',`<button class="btn primary" onclick="newTask()">＋ Schedule Work</button>`)+`<div class="card section">${[...data.tasks].sort((a,b)=>a.due.localeCompare(b.due)).map(t=>`<div class="listrow"><div style="width:115px"><b>${esc(t.due)}</b></div><div style="flex:1"><b>${esc(t.title)}</b><div class="small muted">${esc(t.project)} · ${esc(t.status)}</div></div><span class="badge ${t.priority==='High'?'red':t.priority==='Medium'?'amber':'green'}">${esc(t.priority)}</span></div>`).join('')}</div>`}
function modal(title,body,saveLabel='Save'){const old=document.querySelector('.drawer-backdrop');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div class="drawer-backdrop" onclick="closeDrawer()"></div><aside class="drawer"><button class="close" onclick="closeDrawer()">×</button><h2>${title}</h2>${body}<div style="display:flex;gap:8px;margin-top:24px"><button class="btn primary" onclick="${saveLabel==='Delete'?'closeDrawer()':'closeDrawer()'}">${saveLabel}</button></div></aside>`)}
function newTask(){modal('New Work Item',taskForm({id:'',title:'',project:data.projects[0]?.name||'',status:'Backlog',priority:'Medium',owner:'Me',due:'',progress:0,dependency:''}),'Create');document.querySelector('.drawer .btn.primary').onclick=()=>saveTask('new')}
function editTask(id){const t=data.tasks.find(x=>x.id===id);if(!t)return;modal(`Edit ${t.id}`,taskForm(t),'Save changes');document.querySelector('.drawer .btn.primary').onclick=()=>saveTask(id)}
function taskForm(t){return `<div class="form-grid"><div class="field full"><label>Work item</label><input id="f-title" value="${esc(t.title)}" placeholder="What needs to be done?"></div><div class="field"><label>Project</label><select id="f-project">${data.projects.map(p=>`<option ${p.name===t.project?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Status</label><select id="f-status">${stages.map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select id="f-priority">${['High','Medium','Low'].map(s=>`<option ${s===t.priority?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Assignee</label><input id="f-owner" value="${esc(t.owner||'Me')}"></div><div class="field"><label>Due date</label><input id="f-due" type="date" value="${esc(t.due)}"></div><div class="field"><label>Dependency</label><select id="f-dep"><option value="">None</option>${data.tasks.filter(x=>x.id!==t.id).map(x=>`<option value="${x.id}" ${x.id===t.dependency?'selected':''}>${x.id} — ${esc(x.title)}</option>`).join('')}</select></div><div class="field"><label>Progress %</label><input id="f-progress" type="number" min="0" max="100" value="${t.progress||0}"></div></div><p class="small muted" style="margin-top:18px">Dependency rule: a work item cannot advance if its dependency is incomplete.</p>`}
function saveTask(mode){const id=mode==='new'?`T-${String(data.tasks.length+1).padStart(3,'0')}`:mode;const obj=mode==='new'?{id,title:'',project:'',status:'Backlog',priority:'Medium',owner:'Me',due:'',progress:0,dependency:''}:data.tasks.find(t=>t.id===id);Object.assign(obj,{title:document.getElementById('f-title').value,project:document.getElementById('f-project').value,status:document.getElementById('f-status').value,priority:document.getElementById('f-priority').value,owner:document.getElementById('f-owner').value||'Me',due:document.getElementById('f-due').value,progress:Math.min(100,Math.max(0,Number(document.getElementById('f-progress').value)||0)),dependency:document.getElementById('f-dep').value});if(mode==='new')data.tasks.push(obj);save();closeDrawer();render();toast(mode==='new'?'Work item created.':'Work item updated.')}
function newProject(){modal('New Project',projectForm({name:'',client:'Internal',stage:'Planning',health:'On track',progress:0,due:'',owner:'Me'}),'Create');document.querySelector('.drawer .btn.primary').onclick=()=>saveProject('new')}
function editProject(id){const p=data.projects.find(x=>x.id===id);modal(`Edit ${p.id}`,projectForm(p),'Save changes');document.querySelector('.drawer .btn.primary').onclick=()=>saveProject(id)}
function projectForm(p){return `<div class="form-grid"><div class="field full"><label>Project name</label><input id="p-name" value="${esc(p.name)}"></div><div class="field"><label>Client / Area</label><input id="p-client" value="${esc(p.client)}"></div><div class="field"><label>Stage</label><input id="p-stage" value="${esc(p.stage)}"></div><div class="field"><label>Health</label><select id="p-health"><option ${p.health==='On track'?'selected':''}>On track</option><option ${p.health==='At risk'?'selected':''}>At risk</option><option>Blocked</option></select></div><div class="field"><label>Owner</label><input id="p-owner" value="${esc(p.owner||'Me')}"></div><div class="field"><label>Due date</label><input id="p-due" type="date" value="${esc(p.due)}"></div><div class="field"><label>Progress %</label><input id="p-progress" type="number" min="0" max="100" value="${p.progress||0}"></div></div>`}
function saveProject(mode){const obj=mode==='new'?{id:`P-${String(data.projects.length+1).padStart(3,'0')}`}:data.projects.find(p=>p.id===mode);Object.assign(obj,{name:document.getElementById('p-name').value,client:document.getElementById('p-client').value,stage:document.getElementById('p-stage').value,health:document.getElementById('p-health').value,owner:document.getElementById('p-owner').value||'Me',due:document.getElementById('p-due').value,progress:Math.min(100,Math.max(0,Number(document.getElementById('p-progress').value)||0)});if(mode==='new')data.projects.push(obj);save();closeDrawer();render();toast('Project saved.')}
function newRequirement(){modal('New Requirement',reqForm({title:'',project:data.projects[0]?.name||'',status:'Draft',priority:'Medium',owner:'Me',dependency:''}),'Create');document.querySelector('.drawer .btn.primary').onclick=()=>saveRequirement('new')}
function editRequirement(id){const r=data.requirements.find(x=>x.id===id);modal(`Edit ${r.id}`,reqForm(r),'Save changes');document.querySelector('.drawer .btn.primary').onclick=()=>saveRequirement(id)}
function reqForm(r){return `<div class="form-grid"><div class="field full"><label>Requirement</label><textarea id="r-title" rows="4">${esc(r.title)}</textarea></div><div class="field"><label>Project</label><input id="r-project" value="${esc(r.project)}"></div><div class="field"><label>Status</label><select id="r-status"><option ${r.status==='Draft'?'selected':''}>Draft</option><option ${r.status==='Approved'?'selected':''}>Approved</option><option ${r.status==='Complete'?'selected':''}>Complete</option></select></div><div class="field"><label>Priority</label><select id="r-priority"><option ${r.priority==='High'?'selected':''}>High</option><option ${r.priority==='Medium'?'selected':''}>Medium</option><option ${r.priority==='Low'?'selected':''}>Low</option></select></div><div class="field"><label>Owner</label><input id="r-owner" value="${esc(r.owner||'Me')}"></div><div class="field full"><label>Dependency</label><input id="r-dep" value="${esc(r.dependency||'')}" placeholder="Optional work item ID"></div></div>`}
function saveRequirement(mode){const obj=mode==='new'?{id:`R-${String(data.requirements.length+1).padStart(3,'0')}`}:data.requirements.find(r=>r.id===mode);Object.assign(obj,{title:document.getElementById('r-title').value,project:document.getElementById('r-project').value,status:document.getElementById('r-status').value,priority:document.getElementById('r-priority').value,owner:document.getElementById('r-owner').value||'Me',dependency:document.getElementById('r-dep').value});if(mode==='new')data.requirements.push(obj);save();closeDrawer();render();toast('Requirement saved.')}
function closeDrawer(){document.querySelector('.drawer')?.remove();document.querySelector('.drawer-backdrop')?.remove()}
function resetData(){if(confirm('Reset all dashboard data to the starter workspace?')){data=structuredClone(defaultData);save();render();toast('Demo workspace reset.')}}
function go(p){page=p;render()}
function render(){app.innerHTML=shell()}
render();
